/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frame2;


/**
 *
 * @author Puco
 */
public class robotChooser extends javax.swing.JDialog {

    private int robotType;
    /**
     * Creates new form robotChooser
     */
    public robotChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        robotType = 3;
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
    }

    public int getRobotChooser()
    {
        return robotType;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jRadioButton1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setLabel("BlancoTron1");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(30, 220, 110, 23);

        jRadioButton2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton2.setText("Blancotron2");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(210, 220, 110, 23);

        jRadioButton3.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("BlancoTron3");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(370, 220, 110, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/5.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 30, 70, 72);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/2.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 20, 72, 72);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/3.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 30, 64, 70);

        jProgressBar1.setValue(75);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(70, 120, 70, 14);

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/pw.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 110, 40, 30);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/spd.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 140, 40, 30);

        jProgressBar2.setValue(25);
        jPanel1.add(jProgressBar2);
        jProgressBar2.setBounds(70, 150, 70, 14);

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/cn.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 170, 70, 40);

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("150");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 180, 34, 14);

        jProgressBar3.setValue(45);
        jPanel1.add(jProgressBar3);
        jProgressBar3.setBounds(250, 120, 70, 14);

        jProgressBar4.setValue(75);
        jPanel1.add(jProgressBar4);
        jProgressBar4.setBounds(250, 150, 70, 14);

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("175");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(270, 180, 34, 14);

        jProgressBar5.setValue(35);
        jPanel1.add(jProgressBar5);
        jProgressBar5.setBounds(420, 120, 70, 14);

        jProgressBar6.setValue(35);
        jPanel1.add(jProgressBar6);
        jProgressBar6.setBounds(420, 150, 70, 14);

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("100");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(420, 180, 34, 14);

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/pw.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(380, 110, 40, 30);

        jLabel20.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 51));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/spd.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(380, 140, 40, 30);

        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/cn.png"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(380, 170, 70, 40);

        jLabel22.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/pw.png"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(220, 110, 40, 30);

        jLabel23.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 204, 51));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/spd.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(220, 140, 40, 30);

        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2/cn.png"))); // NOI18N
        jPanel1.add(jLabel24);
        jLabel24.setBounds(220, 170, 70, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 40, 520, 260);

        jButton1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton1.setText("Launch!");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 320, 150, 40);

        jLabel18.setFont(new java.awt.Font("Cordia New", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setText("Chose Your Starter  Robot:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 20, 160, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 410);

        setSize(new java.awt.Dimension(596, 452));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        robotType=2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        robotType=1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        robotType=3;
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(robotChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(robotChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(robotChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(robotChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                robotChooser dialog = new robotChooser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
